### ISSUE TITLE
Publish latest docker image (1.9.0?)

### ISSUE THREAD

**Issue by acidelk** [Telefonica/prometheus-kafka-adapter#101]
Hi.
Please publish latest docker image after this changes: https://github.com/Telefonica/prometheus-kafka-adapter/commit/6a1dbf53779c4adeb6ee4e7fb2981391074966aa
1.8.0 has a critical vulnerabilities :(

**Comment by palmerabollo** [comment]
Duplicate of #109. A new 1.9.0 release with many deps bumped (see #119) has just been published @acidelk
