### ISSUE TITLE
Any plans of supporting reading from Kafka and writing to remote write compatible systems

### ISSUE THREAD

**Issue by rajeshksv** [Telefonica/prometheus-kafka-adapter#120]
If no plans, any recommendation of such tool (if exists) ?

**Comment by palmerabollo** [comment]
No plans. Our focus is to receive metrics from prometheus and write them to kafka.

No sure about alternative tools, I guess it depends on the details of your use case. If you want to read from Kafka, take a look at kafka-connect.
