### ISSUE TITLE
virtual machine environment deployment

### ISSUE THREAD

**Issue by RLJie168** [Telefonica/prometheus-kafka-adapter#125]
Currently, we are not using a Docker container environment. If we want to use the prometheus-kafka-adapter, can we directly compile a zip software package through Go? How can we include the relevant parameters to execute the binary file?

**Comment by palmerabollo** [comment]
You can follow the steps in [the Dockerfile](https://github.com/Telefonica/prometheus-kafka-adapter/blob/master/Dockerfile) and run them in other environment (e.g., your laptop) as long as you have go installed.

You should end up with a prometheus-kafka-adapter binary file.
I hope this helps.
