### ISSUE TITLE
Evaluate alternative kafka libs

### ISSUE THREAD

**Issue by palmerabollo** [Telefonica/prometheus-kafka-adapter#15]

**Comment by johnatannvmd** [comment]
What is the problem with librdkafka? Just curious

**Comment by palmerabollo** [comment]
@johnatannvmd There are no issues with librdkafka. It works well but we wanted to evaluate [sarama](https://github.com/Shopify/sarama) to compare its performance against librdkafka. Any experience in this regard is welcome.
