### ISSUE TITLE
As a chinese developer, how can I run it ? because there we have a wall

### ISSUE THREAD

**Issue by zl1079167478** [Telefonica/prometheus-kafka-adapter#21]

**Comment by palmerabollo** [comment]
What is your issue? If you are not able to download the docker image from docker hub, you can always clone this repository and build the image (`git clone` + `docker build -t telefonica/prometheus-kafka-adapter .`) on your own computer.

Another alternative, if you don't plan to move to another country, would be to use a VPN.

**Comment by palmerabollo** [comment]
ping @zl1079167478
