### ISSUE TITLE
Error when using prometheus-kafka-adapter: 1.2.0

### ISSUE THREAD

**Issue by pengyide** [Telefonica/prometheus-kafka-adapter#22]
{"error":"Local: Queue full","level":"error","msg":"couldn't produce message in kafka","time":"2019-04-22T02:46:06Z"}

**Comment by palmerabollo** [comment]
Hi @pengyide. It looks like an error trying to communicate prometheus-kafka-adapter with your kafka.

Are you sure that your setup (KAFKA_BROKER_LIST, KAFKA_TOPIC) is right? The error "couldn't produce message in kafka" means that prometheus-kafka-adapter is not able to offload the metrics it receives from prometheus onto kafka.

Can you verify that your Kafka is reachable and that you can write messages to the topic with another client (e.g. kafka-console-producer)?

**Comment by pengyide** [comment]
Hi，I'm very happy to have received your response。I want to know what "KAFKA_BROKER_LIST" means, the following is my information，host IP is 10.121.11.15,

thanks again!




At 2019-04-22 14:40:00, "Guido García" <notifications@github.com> wrote:


Hi @pengyide. It looks like an error trying to communicate prometheus-kafka-adapter with your kafka.

Are you sure that your setup (KAFKA_BROKER_LIST, KAFKA_TOPIC) is right? The error "couldn't produce message in kafka" means that prometheus-kafka-adapter is not able to offload the metrics it receives from prometheus onto kafka.

Can you verify that your Kafka is reachable and that you can write messages to the topic with another client (e.g. kafka-console-producer)?

**Comment by palmerabollo** [comment]
It's the kafka host:port you need to configure as an environment variable as described at https://github.com/Telefonica/prometheus-kafka-adapter#prometheus-kafka-adapter-1

**Comment by pengyide** [comment]
OK，very  thanks for you.
