### ISSUE TITLE
Receive failed: Disconnected

### ISSUE THREAD

**Issue by pengyide** [Telefonica/prometheus-kafka-adapter#23]
When I run this adapter, the log shows the following error.

%3|1556163317.796|FAIL|rdkafka#producer-1| [thrd:10.121.218.13:30902/bootstrap]: 10.121.218.13:30902/1001: Receive failed: Disconnected
%3|1556163317.796|ERROR|rdkafka#producer-1| [thrd:10.121.218.13:30902/bootstrap]: 10.121.218.13:30902/1001: Receive failed: Disconnected
%3|1556163317.796|ERROR|rdkafka#producer-1| [thrd:10.121.218.13:30902/bootstrap]: 1/1 brokers are down

What is this because of what? 
Thanks!

**Comment by palmerabollo** [comment]
@pengyide the most likely cause is that the only Kafka broker (1/1) that you have is down or not reachable. This is why it says it is "Disconnected". Make sure that your Kafka broker is up and that you can connect to it (for example, using kafka-console-producer) from the same machine where you run prometheus-kafka-adapter.

**Comment by pengyide** [comment]
Thanks again. I want to know what data the prometheus transmitted via remote_write is placed under the directory of this adapter.
Thanks very much!
