### ISSUE TITLE
I want to know how to confirm that this adapter received the data sent by prometheus.

### ISSUE THREAD

**Issue by pengyide** [Telefonica/prometheus-kafka-adapter#24]
I want to know how to confirm that this adapter received the data sent by prometheus.

**Comment by palmerabollo** [comment]
You just need to run it with LOG_LEVEL=debug to see everything it recieves. The magic is done in this line if I'm not wrong https://github.com/Telefonica/prometheus-kafka-adapter/blob/master/prometheus.go#L23.

**Comment by pengyide** [comment]
oh,thanks for you!






At 2019-04-29 23:50:57, "Guido García" <notifications@github.com> wrote:


You just need to run it with LOG_LEVEL=debug to see everything it recieves. The magic is done in this line if I'm not wrong https://github.com/Telefonica/prometheus-kafka-adapter/blob/master/prometheus.go#L23.
