### ISSUE TITLE
 Error when using prometheus-kafka-adapter 1.4

### ISSUE THREAD

**Issue by maristeslk** [Telefonica/prometheus-kafka-adapter#29]
too much error 
{"fields.time":"2019-12-31T07:57:07Z","ip":"127.0.0.1","latency":1373766,"level":"info","method":"POST","msg":"","path":"/receive","status":200,"time":"2019-12-31T15:57:07+08:00","user-agent":"Prometheus/2.12.0"}
{"fields.time":"2019-12-31T07:57:07Z","ip":"127.0.0.1","latency":12182080,"level":"info","method":"POST","msg":"","path":"/receive","status":200,"time":"2019-12-31T15:57:07+08:00","user-agent":"Prometheus/2.12.0"}
{"fields.time":"2019-12-31T07:57:07Z","ip":"127.0.0.1","latency":1598273,"level":"info","method":"POST","msg":"","path":"/receive","status":200,"time":"2019-12-31T15:57:07+08:00","user-agent":"Prometheus/2.12.0"}
{"fields.time":"2019-12-31T07:57:07Z","ip":"127.0.0.1","latency":13521915,"level":"info","method":"POST","msg":"","path":"/receive","status":200,"time":"2019-12-31T15:57:07+08:00","user-agent":"Prometheus/2.12.0"}
{"fields.time":"2019-12-31T07:57:07Z","ip":"127.0.0.1","latency":200815888,"level":"info","method":"POST","msg":"","path":"/receive","status":500,"time":"2019-12-31T15:57:07+08:00","user-agent":"Prometheus/2.12.0"}
{"fields.time":"2019-12-31T07:57:07Z","ip":"127.0.0.1","latency":200013963,"level":"info","method":"POST","msg":"","path":"/receive","status":500,"time":"2019-12-31T15:57:07+08:00","user-agent":"Prometheus/2.12.0"}
{"fields.time":"2019-12-31T07:57:07Z","ip":"127.0.0.1","latency":2004606,"level":"info","method":"POST","msg":"","path":"/receive","status":500,"time":"2019-12-31T15:57:07+08:00","user-agent":"Prometheus/2.12.0"}

**Comment by chijiajian** [comment]
too many 500 http return code
{"fields.time":"2020-01-09T02:35:41Z","ip":"10.130.62.12","latency":11423261,"level":"info","method":"POST","msg":"","path":"/receive","status":500,"time":"2020-01-09T10:35:41+08:00","user-agent":"Prometheus/2.7.1"}
{"fields.time":"2020-01-09T02:35:41Z","ip":"10.130.62.12","latency":11216110,"level":"info","method":"POST","msg":"","path":"/receive","status":500,"time":"2020-01-09T10:35:41+08:00","user-agent":"Prometheus/2.7.1"}

**Comment by palmerabollo** [comment]
@chijiajian We'd need additional info to reproduce the issue. Can you share:
- your prometheus-kafka-adapter config
- the version you are using

Moreover, try to set `LOG_LEVEL=true` and `GIN_MODE=debug` to turn debug logs on. They might be helpful to debug the issue.

**Comment by palmerabollo** [comment]
Unable to reproduce. Please, reopen if needed.
