### ISSUE TITLE
Bump versions of librdkafka and confluent-kafka-go ?

### ISSUE THREAD

**Issue by obitech** [Telefonica/prometheus-kafka-adapter#34]
We're using prometheus-kafka-adapter `1.4.1` internally with a `kafka_2.11-2.0.0` broker setup and because of the (what I assume) older version of `librdkafka` and `confluent-kafka-go` on the producer side, messages need to be converted by the consumer.

>  Message conversions introduce a processing overhead as messages between the Kafka clients and brokers require conversion in order to be understood by both parties. Any produce message conversions being performed indicates that some Kafka producers are using a different version of Kafka to the Kafka brokers. To avoid unnecessary message conversions, ensure all Kafka clients are using the same version of Kafka as the Kafka brokers. 

Would it create any issue to bump the versions of both modules for prometheus-kafka-adapter? 

```diff
-       github.com/confluentinc/confluent-kafka-go v1.0.0
+       github.com/confluentinc/confluent-kafka-go v1.3.0
-       github.com/edenhill/librdkafka v1.0.1
+       github.com/edenhill/librdkafka v1.3.0
```

I did some tests locally and it builds fine and seems to be working.

**Comment by palmerabollo** [comment]
@obitech Yes, please, feel free to send a pull request. We can do some tests as well and publish a new 1.5.0 release if everything goes well. Thank you, Alexander.
