### ISSUE TITLE
Fails when kafka is not using ssl

### ISSUE THREAD

**Issue by LoicLeGal** [Telefonica/prometheus-kafka-adapter#37]
if ssl is not used in kafka, ssl.fields should not be added in the context for libkafka:
https://github.com/Telefonica/prometheus-kafka-adapter/blob/4e89c6a5c0d5183f457aea17d117cf05cb9e11a5/main.go#L37

**Comment by palmerabollo** [comment]
Thanks @LoicLeGal, you are right. They should be moved to the conditional below https://github.com/Telefonica/prometheus-kafka-adapter/blob/4e89c6a5c0d5183f457aea17d117cf05cb9e11a5/main.go#L44

Could you please send a pull request with the fix?

**Comment by LoicLeGal** [comment]
Fixed in Telefonica/prometheus-kafka-adapter/pull/38 (and PR also fixed :) )

**Comment by palmerabollo** [comment]
Merged. A new release 1.6.0 has just been published. Thank you for your help.
