### ISSUE TITLE
How to run prometheus-kafka-adapter on a VM

### ISSUE THREAD

**Issue by carineKanouo** [Telefonica/prometheus-kafka-adapter#45]
Hi, i don't use container and i want tu know how to setup prometheus-kafka-adapter on a vm and make it run properly

Thank you

**Comment by jpfe-tid** [comment]
Hi @carineKanouo,

1. Install `librdkafka` with your system package manager.
2. Install Go, download this repo and switch to its directory.
3. Run `go build -o prometheus-kafka-adapter`.
4. Follow the README for a list of environment variables to be exported.
5. Execute the binary interactively or through a service manager (e.g. systemd).

Checkout the Dockerfile for reproducible build commands.

https://github.com/Telefonica/prometheus-kafka-adapter/blob/master/Dockerfile
