### ISSUE TITLE
adapter not collecting prometheus metrics 

### ISSUE THREAD

**Issue by KennethNagin** [Telefonica/prometheus-kafka-adapter#48]
I've installed the prometheus-kafka-adapter using your helm chart.  However I am having no success getting it to work.
When print out its log get lots of messages like:

> {"fields.time":"2020-06-30T11:41:41Z","ip":"10.45.216.154","latency":1407190,"level":"info","method":"GET","msg":"","path":"/metrics","status":200,"time":"2020-06-30T11:41:41Z","user-agent":"kube-probe/1.16"}

However there is nothing related to the prometheus metrics.
When I use portforwarding to browse to its home page I get a "404 page not found".
I also do not see anything in the kafka topic metrics.

These are the relate kubectl get svc entries

```
kafka                           ClusterIP      172.21.234.145   <none>          9092/TCP 
prometheus-kafka-adapter        ClusterIP      172.21.242.209   <none>          8080/TCP 
```

The prometheus values setting:

```yaml
server:
  remotewrite: http:\\prometheus-kafka-adapter:8080\receive
```

Any suggests?

**Comment by palmerabollo** [comment]
@KennethNagin any logs in prometheus? Is the remotewrite URL ok? It is using the wrong bars ("\\" instead of "/"). Also, make sure you are using [`remote_write`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) instead of `remotewrite` in your prometheus configuration.

**Comment by palmerabollo** [comment]
I'm closing this issue. It looks like a problem in prometheus' config. @KennethNagin please reopen if needed.

**Comment by KennethNagin** [comment]
For the record.  This is the form that works for stable/prometheus values.yaml
server:
        remoteWrite:
                -  url: http://prometheus-kafka-adapter:8080/receive
