### ISSUE TITLE
Can this be used with a load balancer

### ISSUE THREAD

**Issue by johnseekins** [Telefonica/prometheus-kafka-adapter#66]
It isn't clear from the docs, but is it possible to put prometheus-kafka-adapter behind a load balancer?

I would imagine it largely depends on how `remote_write` works in Prometheus itself...but even a LEAST_CONNECTED or SOURCE_IP balancing strategy _might_ work?

**Comment by palmerabollo** [comment]
Hi @johnseekins. Yes. Prometheus-kafka-adapter is stateless. You can use any load balancing strategy. We use several instances in our production environment with a Kubernetes service in front of them, that acts as a load balancer.

**Comment by johnseekins** [comment]
Perfect. Thanks.
