### ISSUE TITLE
Include support for kerberos?

### ISSUE THREAD

**Issue by billmania42** [Telefonica/prometheus-kafka-adapter#70]
Can this code support using GSSAPI (kerberos)?

**Comment by palmerabollo** [comment]
Hi @billmania42.
We have no plans to support it but we are open to contributions if you feel like adding/maintaining it. We already support SASL/SCRAM (via `KAFKA_SECURITY_PROTOCOL` and `KAFKA_SASL_MECHANISM` env vars) so I guess it's doable, but I have no experience with GSSAPI so I can't tell how hard it would be.

**Comment by billmania42** [comment]
Ok, thank you.

**Comment by palmerabollo** [comment]
I'm closing the issue. Thank you for the idea.

**Comment by billmania42** [comment]
I will give this a shot.  I am going to test this out.  At that point open a PR.  Thanks
