### ISSUE TITLE
请问下 windows可以打包吗，confluent-kafka-go在windows下似乎不能运行

### ISSUE THREAD

**Issue by JasonZhang1991** [Telefonica/prometheus-kafka-adapter#74]

**Comment by palmerabollo** [comment]
Hi @JasonZhang1991. I've never tried it on Windows, but **it should work**. Please let us know all the details you have about the error you see when you package the app on Windows.

_(You could also use the Docker image if you don't want to compile it yourself)_

**Comment by JasonZhang1991** [comment]
it noticed some kafka package not found ,i have tried it on wsl based on debian and it worked
