### ISSUE TITLE
Prometheus kafka integration on bare metal 

### ISSUE THREAD

**Issue by MuhammadMunir12** [Telefonica/prometheus-kafka-adapter#88]
I want to integrate prometheus with kafka in sucha way that prometheus alerts are sent to kafka broker as producer and consumer get the alerts as message in kafka queue. It would be highly appreciated if anyone can guide on how to do this.

**Comment by palmerabollo** [comment]
Hi @MuhammadMunir12 , take a look at how prometheus-kafka-adapter is built https://github.com/Telefonica/prometheus-kafka-adapter/blob/master/Dockerfile#L9. Once you have it compiled, you should be able to run the binary on bare metal.
